# Generated by Django 3.1.2 on 2020-11-07 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(max_length=16)),
                ('secret', models.CharField(max_length=32)),
                ('access_token', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(max_length=16)),
                ('context_id', models.CharField(max_length=32)),
                ('message', models.CharField(max_length=16384)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(max_length=64)),
                ('user_id', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('gender', models.CharField(max_length=16)),
                ('birth_day', models.CharField(max_length=16)),
                ('birth_time', models.CharField(max_length=16)),
                ('status', models.CharField(max_length=16)),
                ('fate_num', models.CharField(max_length=16)),
            ],
        ),
    ]
