# Generated by Django 3.1.2 on 2020-11-07 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fate_num',
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, default=1000, primary_key=True, serialize=False),
        ),
    ]
